# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PCAUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class PCAUI(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(787, 623)
        MainWindow.setStyleSheet("MainWindow{\n"
"background-color: rgb(0, 0, 0);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setStyleSheet("#centralwidget{background-color:rgb(0, 0, 0) }\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalWidget_4.setObjectName("verticalWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalWidget_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pcaPict = QtWidgets.QGraphicsView(self.verticalWidget_4)
        self.pcaPict.setObjectName("pcaPict")
        self.verticalLayout_4.addWidget(self.pcaPict)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.draw = QtWidgets.QPushButton(self.verticalWidget_4)
        self.draw.setObjectName("draw")
        self.horizontalLayout_7.addWidget(self.draw)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.gridLayout.addWidget(self.verticalWidget_4, 3, 1, 1, 1)
        self.paraForm = QtWidgets.QWidget(self.centralwidget)
        self.paraForm.setStyleSheet("")
        self.paraForm.setObjectName("paraForm")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.paraForm)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.dataPath = QtWidgets.QLineEdit(self.paraForm)
        self.dataPath.setObjectName("dataPath")
        self.gridLayout_4.addWidget(self.dataPath, 1, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.paraForm)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("#label_3{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 1, 2, 1, 1)
        self.selectData = QtWidgets.QToolButton(self.paraForm)
        self.selectData.setObjectName("selectData")
        self.gridLayout_4.addWidget(self.selectData, 1, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 1, 5, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.paraForm)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("#label_5{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 3, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 2, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem5, 3, 0, 1, 1)
        self.newPath = QtWidgets.QLineEdit(self.paraForm)
        self.newPath.setObjectName("newPath")
        self.gridLayout_4.addWidget(self.newPath, 2, 3, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem6, 3, 5, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem7, 2, 5, 1, 1)
        self.ratio = QtWidgets.QLineEdit(self.paraForm)
        self.ratio.setObjectName("ratio")
        self.gridLayout_4.addWidget(self.ratio, 3, 3, 1, 1)
        self.selectNew = QtWidgets.QToolButton(self.paraForm)
        self.selectNew.setObjectName("selectNew")
        self.gridLayout_4.addWidget(self.selectNew, 2, 4, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem8, 4, 0, 1, 1)
        self.start = QtWidgets.QPushButton(self.paraForm)
        self.start.setObjectName("start")
        self.gridLayout_4.addWidget(self.start, 4, 3, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem9, 4, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.paraForm)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("#label_2{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 2, 2, 1, 1)
        self.gridLayout.addWidget(self.paraForm, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setStyleSheet("#label{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(102, 102, 102);\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.verticalWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalWidget_3.setObjectName("verticalWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalWidget_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.verticalWidget_3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.widget = QtWidgets.QWidget(self.verticalWidget_3)
        self.widget.setObjectName("widget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("#label_4{color:white}")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.verticalLayout_3.addWidget(self.widget)
        self.gridLayout.addWidget(self.verticalWidget_3, 1, 1, 1, 1)
        self.verticalWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalWidget_2.setObjectName("verticalWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalWidget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cov = QtWidgets.QTextBrowser(self.verticalWidget_2)
        self.cov.setObjectName("cov")
        self.verticalLayout_2.addWidget(self.cov)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem12)
        self.label_6 = QtWidgets.QLabel(self.verticalWidget_2)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("#label_6{color:white}")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem13)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.gridLayout.addWidget(self.verticalWidget_2, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 787, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.draw.setText(_translate("MainWindow", "绘图"))
        self.label_3.setText(_translate("MainWindow", "数据文件"))
        self.selectData.setText(_translate("MainWindow", "..."))
        self.label_5.setText(_translate("MainWindow", "降维比例"))
        self.selectNew.setText(_translate("MainWindow", "..."))
        self.start.setText(_translate("MainWindow", "start"))
        self.label_2.setText(_translate("MainWindow", "降维文件"))
        self.label.setText(_translate("MainWindow", "PCA算法演示"))
        self.label_4.setText(_translate("MainWindow", "变换矩阵A"))
        self.label_6.setText(_translate("MainWindow", "PCA分析结果"))

